export const users = [
  {
    name: "Alice Johnson",
    age: 28,
    hobby: "Painting",
    email: "alice@example.com",
  },
  {
    name: "Bob Smith",
    age: 35,
    hobby: "Gardening",
    email: "bob@example.com",
  },
  {
    name: "Claire Brown",
    age: 22,
    hobby: "Reading",
    email: "claire@example.com",
  },
  {
    name: "David Lee",
    age: 40,
    hobby: "Cooking",
    email: "david@example.com",
  },
  {
    name: "Eva Garcia",
    age: 31,
    hobby: "Photography",
    email: "eva@example.com",
  },
  {
    name: "Frank Adams",
    age: 27,
    hobby: "Playing Guitar",
    email: "frank@example.com",
  },
  {
    name: "Grace Wilson",
    age: 24,
    hobby: "Dancing",
    email: "grace@example.com",
  },
  {
    name: "Henry Turner",
    age: 33,
    hobby: "Hiking",
    email: "henry@example.com",
  },
  {
    name: "Isabella Martinez",
    age: 29,
    hobby: "Traveling",
    email: "isabella@example.com",
  },
  {
    name: "Jack Robinson",
    age: 26,
    hobby: "Playing Chess",
    email: "jack@example.com",
  },
  {
    name: "Karen Hall",
    age: 37,
    hobby: "Yoga",
    email: "karen@example.com",
  },
  {
    name: "Liam Miller",
    age: 23,
    hobby: "Swimming",
    email: "liam@example.com",
  },
  {
    name: "Mia Scott",
    age: 30,
    hobby: "Writing",
    email: "mia@example.com",
  },
  {
    name: "Noah White",
    age: 32,
    hobby: "Playing Tennis",
    email: "noah@example.com",
  },
  {
    name: "Olivia Harris",
    age: 25,
    hobby: "Singing",
    email: "olivia@example.com",
  },
  {
    name: "Peter Green",
    age: 34,
    hobby: "Cycling",
    email: "peter@example.com",
  },
  {
    name: "Quinn Turner",
    age: 28,
    hobby: "Cooking",
    email: "quinn@example.com",
  },
  {
    name: "Ryan Adams",
    age: 31,
    hobby: "Playing Piano",
    email: "ryan@example.com",
  },
  {
    name: "Sophia Lewis",
    age: 27,
    hobby: "Gardening",
    email: "sophia@example.com",
  },
  {
    name: "Thomas Clark",
    age: 36,
    hobby: "Running",
    email: "thomas@example.com",
  },
  {
    name: "Uma Patel",
    age: 24,
    hobby: "Painting",
    email: "uma@example.com",
  },
  {
    name: "Victor Kim",
    age: 29,
    hobby: "Playing Violin",
    email: "victor@example.com",
  },
  {
    name: "Wendy Adams",
    age: 33,
    hobby: "Reading",
    email: "wendy@example.com",
  },
  {
    name: "Xander Brown",
    age: 26,
    hobby: "Photography",
    email: "xander@example.com",
  },
  {
    name: "Yara Garcia",
    age: 30,
    hobby: "Dancing",
    email: "yara@example.com",
  },
  {
    name: "Zoe Turner",
    age: 25,
    hobby: "Hiking",
    email: "zoe@example.com",
  },
];
